version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3001:3001"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"   # map container port 80 to host 3000
    depends_on:
      - backend
