name: Build & Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set image tag
        run: |
          echo "IMAGE_TAG=build-${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: Build backend image
        run: |
          docker build -t divaysnhujain/monitoring-backend:${{ env.IMAGE_TAG }} ./backend
          docker push divaysnhujain/monitoring-backend:${{ env.IMAGE_TAG }}

      - name: Build frontend image
        run: |
          docker build -t divaysnhujain/monitoring-frontend:${{ env.IMAGE_TAG }} ./frontend
          docker push divaysnhujain/monitoring-frontend:${{ env.IMAGE_TAG }}
